# Generated by Django 4.0.4 on 2022-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='myemail',
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
