# Generated by Django 4.0.4 on 2022-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_email_message_myemail_alter_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
